feat: setup tooling (#658)
* feat: setup tooling

* fix: all the container things

* fix: all the container things

* fix: all the flake things

* fix: all the flake things

* fix: all the flake things

* fix: all the flake things

* fix: all the flake things

* fix: multiplatform docker

* fix: try using newlines

* fix: try using newlines

* fix: ignore kics error

* fix: user non-root user

* fix: heredoc

* fix: heredoc

* fix: heredoc

* fix: container scan

* fix: container scan

* fix: container scan

* fix: container scan

* fix: container scan

* fix: code scan

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -23,7 +23,7 @@ jobs:
       contents: write
       checks: write
       pull-requests: write
-    timeout-minutes: 60
+    timeout-minutes: 15
     steps:
       - uses: actions/checkout@v4.2.2
       - uses: oxsecurity/megalinter/flavors/cupcake@v8.7.0
@@ -42,13 +42,11 @@ jobs:
         with:
           sarif_file: megalinter-reports/megalinter-report.sarif
   BuildContainer:
-    # TODO: fix docker builds
-    if: false
     runs-on: ubuntu-latest
     permissions:
       contents: read
       packages: write
-    timeout-minutes: 60
+    timeout-minutes: 30
     outputs:
       version: ${{ steps.semver.outputs.version }}
       meta_json: ${{ steps.meta.outputs.json }}
@@ -65,7 +63,8 @@ jobs:
       - name: Get Next Version
         id: semver
         uses: ietf-tools/semver-action@v1.10.1
-        if: github.event_name == 'workflow_dispatch' && github.ref_name == github.event.repository.default_branch
+        # TODO: convert this for push events on tag
+        if: false
         with:
           token: ${{ github.token }}
           branch: ${{ github.event.repository.default_branch }} # TODO: fix so that this works for cron
@@ -85,9 +84,11 @@ jobs:
           tags: |
             type=ref,event=branch,enable=${{ github.event_name == 'push' }}
             type=ref,event=pr,enable=${{ github.event_name == 'pull_request' }}
-            type=semver,pattern={{version}},value=${{ steps.semver.outputs.version }},enable=${{ github.event_name == 'workflow_dispatch' && github.ref_name == github.event.repository.default_branch }}
-            type=semver,pattern={{major}}.{{minor}},value=${{ steps.semver.outputs.version }},enable=${{ github.event_name == 'workflow_dispatch' && github.ref_name == github.event.repository.default_branch }}
+          # TODO: convert this for push events on tag
+          # type=semver,pattern={{version}},value=${{ steps.semver.outputs.version }},enable=${{ github.event_name == 'workflow_dispatch' && github.ref_name == github.event.repository.default_branch }}
+          # type=semver,pattern={{major}}.{{minor}},value=${{ steps.semver.outputs.version }},enable=${{ github.event_name == 'workflow_dispatch' && github.ref_name == github.event.repository.default_branch }}
       - uses: docker/build-push-action@v6.18.0
+        id: docker_build
         with:
           platforms: linux/amd64,linux/arm64
           push: true
@@ -98,6 +99,15 @@ jobs:
           sbom: true
           cache-from: type=gha
           cache-to: type=gha,mode=max
+      - uses: anchore/scan-action@v6
+        id: scan
+        with:
+          image: ${{ fromJSON(steps.docker_build.outputs.metadata).image.name }}
+          cache-db: true
+      - name: upload Anchore scan SARIF report
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: ${{ steps.scan.outputs.sarif }}
   BuildAndPublish:
     runs-on: ubuntu-latest
     permissions:
@@ -144,3 +154,74 @@ jobs:
       - name: Publish
         run: |
           env CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }} nix run .#wrangler -- pages publish --project-name vyas-n --branch "$(git branch --show-current)" ./result
+  CodeQLAnalyze:
+    name: CodeQL Analyze (${{ matrix.language }})
+    # Runner size impacts CodeQL analysis time. To learn more, please see:
+    #   - https://gh.io/recommended-hardware-resources-for-running-codeql
+    #   - https://gh.io/supported-runners-and-hardware-resources
+    #   - https://gh.io/using-larger-runners (GitHub.com only)
+    # Consider using larger runners or machines with greater resources for possible analysis time improvements.
+    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
+    permissions:
+      # required for all workflows
+      security-events: write
+      # required to fetch internal or private CodeQL packs
+      packages: read
+      # only required for workflows in private repositories
+      # actions: read
+      # contents: read
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          - language: actions
+            build-mode: none
+        # CodeQL supports the following values keywords for 'language': 'actions', 'c-cpp', 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'swift'
+        # Use `c-cpp` to analyze code written in C, C++ or both
+        # Use 'java-kotlin' to analyze code written in Java, Kotlin or both
+        # Use 'javascript-typescript' to analyze code written in JavaScript, TypeScript or both
+        # To learn more about changing the languages that are analyzed or customizing the build mode for your analysis,
+        # see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning.
+        # If you are analyzing a compiled language, you can modify the 'build-mode' for that language to customize how
+        # your codebase is analyzed, see https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages
+    steps:
+      - uses: actions/checkout@v4
+
+      # Add any setup steps before running the `github/codeql-action/init` action.
+      # This includes steps like installing compilers or runtimes (`actions/setup-node`
+      # or others). This is typically only required for manual builds.
+      # - name: Setup runtime (example)
+      #   uses: actions/setup-example@v1
+
+      # Initializes the CodeQL tools for scanning.
+      - uses: github/codeql-action/init@v3
+        with:
+          languages: ${{ matrix.language }}
+          build-mode: ${{ matrix.build-mode }}
+          # If you wish to specify custom queries, you can do so here or in a config file.
+          # By default, queries listed here will override any specified in a config file.
+          # Prefix the list here with "+" to use these queries and those in the config file.
+
+          # For more details on CodeQL's query packs, refer to: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+          # queries: security-extended,security-and-quality
+
+      # If the analyze step fails for one of the languages you are analyzing with
+      # "We were unable to automatically build your code", modify the matrix above
+      # to set the build mode to "manual" for that language. Then modify this step
+      # to build your code.
+      # ℹ️ Command-line programs to run using the OS shell.
+      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
+      - if: matrix.build-mode == 'manual'
+        shell: bash
+        run: |
+          echo 'If you are using a "manual" build mode for one or more of the' \
+            'languages you are analyzing, replace this with the commands to build' \
+            'your code, for example:'
+          echo '  make bootstrap'
+          echo '  make release'
+          exit 1
+
+      - name: Perform CodeQL Analysis
+        uses: github/codeql-action/analyze@v3
+        with:
+          category: "/language:${{matrix.language}}"
